defaults:
  - _self_
  - dataset: cedr
  - model: rubert-tiny2
  - optimizer: adam
  - trainer: ${model}-${dataset}

project_name: "VKR"

log_wandb: False

task: eval
trained_model_name: test
# task: train
